### ISSUE TITLE
Impossible de lancer la reconnaissance vocale

### ISSUE THREAD

**Issue by N0ury** [1ud0v1c/VoiceApplication#1]
Salut,

Dès que je clique sur "Reconnaissance Vocale" j'obtiens la log suivante:

```
I/ActivityManager( 2410): START u0 {act=android.speech.action.RECOGNIZE_SPEECH cmp=com.google.android.googlequicksearchbox/com.google.android.voicesearch.intentapi.IntentApiActivity (has extras)} from uid 10131 on display 0
V/WindowManager( 2410): addAppToken: AppWindowToken{f159251 token=Token{7d3bb78 ActivityRecord{39cfc4db u0 com.google.android.googlequicksearchbox/com.google.android.voicesearch.intentapi.IntentApiActivity t2138}}} to stack=1 task=2138 at 1
D/audio_hw_primary( 1983): select_output_device: AUDIO_DEVICE_OUT_SPEAKER
V/WindowManager( 2410): Adding window Window{36fbd3b7 u0 com.google.android.googlequicksearchbox/com.google.android.voicesearch.intentapi.IntentApiActivity} at 4 of 13 (after Window{2e1ce06a u0 fr.borntocode.lud00.voiceapplication/fr.borntocode.lud00.voiceapplication.MainActivity})
W/Bundle  ( 8427): Key android.speech.extra.LANGUAGE expected String but value was a java.util.Locale.  The default value <null> was returned.
W/Bundle  ( 8427): Attempt to cast generated internal exception:
W/Bundle  ( 8427): java.lang.ClassCastException: java.util.Locale cannot be cast to java.lang.String
W/Bundle  ( 8427):  at android.os.BaseBundle.getString(BaseBundle.java:921)
W/Bundle  ( 8427):  at android.content.Intent.getStringExtra(Intent.java:5258)
W/Bundle  ( 8427):  at com.google.android.apps.gsa.extradex.intentapi.e.<init>(IntentApiParams.java:55)
W/Bundle  ( 8427):  at com.google.android.apps.gsa.extradex.intentapi.a.<init>(IntentApiAdapterImpl.java:86)
W/Bundle  ( 8427):  at com.google.android.apps.gsa.extradex.intentapi.EntryPoint.createIntentApi(EntryPoint.java:32)
W/Bundle  ( 8427):  at com.google.android.voicesearch.intentapi.IntentApiActivity$1.onSuccess(IntentApiActivity.java:1142)
W/Bundle  ( 8427):  at com.google.common.util.concurrent.ak$2.run(Futures.java:1132)
W/Bundle  ( 8427):  at com.google.android.apps.gsa.shared.util.concurrent.a.z$1.run(TaskRunnerImpl.java:607)
W/Bundle  ( 8427):  at android.os.Handler.handleCallback(Handler.java:739)
W/Bundle  ( 8427):  at android.os.Handler.dispatchMessage(Handler.java:95)
W/Bundle  ( 8427):  at android.os.Looper.loop(Looper.java:135)
W/Bundle  ( 8427):  at android.app.ActivityThread.main(ActivityThread.java:5374)
W/Bundle  ( 8427):  at java.lang.reflect.Method.invoke(Native Method)
W/Bundle  ( 8427):  at java.lang.reflect.Method.invoke(Method.java:372)
W/Bundle  ( 8427):  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
W/Bundle  ( 8427):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
W/IntentApiController( 8427): Falling back to default language with no additional languages

```

Puis ça boucle sur une demande de parler

Une idée ?

Merci

Noury

**Comment by 1ud0v1c** [comment]
Salut,

Alors il semblerait tout simplement que la fonction Locale.getDefault() dans la méthode promptSpeechInput(), ne retourne pas ce qu'il faut. Sur ce [thread](http://stackoverflow.com/questions/28866872/google-speech-to-text-throwing-java-lang-classcastexception) de stackoverflow, il semblerait que quelqu'un ait déjà eut le souci. Ce dernier conseille alors de hardcoder la valeur transmise comme ceci pour le français :

`intent.putExtra(RecognizerIntent.EXTRA_LANGUAGE, "fr-FR");
` 

Peux-tu également me dire quel appareil et version d'Android tu as utilisé que j'essaye d'effectuer quelques tests également :) ?

Bonne soirée,
1ud0v1c

**Comment by N0ury** [comment]
Salut,

Merci pour ta réponse.
C’est curieux, j’ai ajouté un Log.d("AAAA","getdefault="+Locale.getDefault());
et j’obtiens:
D/AAAA    (14204): getdefault=fr_FR

Par contre si je mets:
intent.putExtra(RecognizerIntent.EXTRA_LANGUAGE, "fr-FR");
Je n’ai plus le plantage.

Malheureusement, je ne peux pas aller beaucoup plus loin. Après le message « Vous pouvez parler », j’ai le message « Appuyez pour parler"

Les messages ne sont pas explicites, les voici au cas où:

I/ActivityManager( 2410): START u0 {act=android.speech.action.RECOGNIZE_SPEECH cmp=com.google.android.googlequicksearchbox/com.google.android.voicesearch.intentapi.IntentApiActivity (has extras)} from uid 10132 on display 0
V/WindowManager( 2410): addAppToken: AppWindowToken{274e12e token=Token{3d87b7a9 ActivityRecord{2fbc3f30 u0 com.google.android.googlequicksearchbox/com.google.android.voicesearch.intentapi.IntentApiActivity t2161}}} to stack=1 task=2161 at 1
D/audio_hw_primary( 1983): select_output_device: AUDIO_DEVICE_OUT_SPEAKER
V/WindowManager( 2410): Adding window Window{5e1e5c u0 com.google.android.googlequicksearchbox/com.google.android.voicesearch.intentapi.IntentApiActivity} at 4 of 13 (after Window{3bed917 u0 fr.borntocode.lud00.voiceapplication/fr.borntocode.lud00.voiceapplication.MainActivity})
I/ActivityManager( 2410): Displayed com.google.android.googlequicksearchbox/com.google.android.voicesearch.intentapi.IntentApiActivity: +222ms (total +9s572ms)
I/AudioRouter(25818): Route changed: ROUTE_NO_AUDIO->ROUTE_NO_BLUETOOTH,CONNECTION_TYPE_NONE->CONNECTION_TYPE_NONE
W/LocationOracle(25818): Best location was null
I/MediaFocusControl( 2410):  AudioFocus  requestAudioFocus() from android.media.AudioManager@902bf52com.google.android.apps.gsa.speech.audio.c.a$1@37e2a223 req=4flags=0x0
W/CronetAsyncHttpEngine(25818): Upload request without a content type.
W/LocationOracle(25818): Best location was null
W/LocationOracle(25818): Best location was null
I/MicrophoneInputStream(25818): mic_starting com.google.android.apps.gsa.speech.audio.ah@2cf9dc2
W/native  (25818): :0 score_cache_ref not set. Using deprecated score cache creation.
I/OMXClient(25818): Using client-side OMX mux.
I/AudioFlinger( 1983): AudioFlinger's thread 0x41a78008 ready to run
E/SEC_COMP_REGS(25818): .
E/SEC_COMP_REGS(25818): ..
E/SEC_COMP_REGS(25818): libOMX.SEC.AVC.Decoder.so
E/SEC_COMP_REGS(25818): Path & libName : /system/lib/omx/libOMX.SEC.AVC.Decoder.so
I/FavoriteContactNamesSup(25818): get()
I/FavoriteContactNamesSup(25818): get() : Cache hit
D/iNemoSensor( 2410): setDelay(): handle(0), en(66667000)
I/iNemoSensor( 2410): skip update_delay wanted_accel = 66667000 current delay = 66667000
D/iNemoSensor( 2410): setDelay(): handle(0), en(66667000)
I/iNemoSensor( 2410): skip update_delay wanted_accel = 66667000 current delay = 66667000
I/iNemoSensor( 2410): enable(): handle(1), en(1), what(2)
D/iNemoSensor( 2410): enable(): MASK_ACC (1) MASK_MAG (4) MASK_GYR (0), MASK_UMAG(0)
D/iNemoSensor( 2410): enable(): mEnAcc(1) mEnMag(1) mEnGyr(0), mEUMag(0)
I/iNemoSensor( 2410): skip update_delay wanted_accel = 66667000 current delay = 66667000
D/iNemoSensor( 2410): setDelay(): handle(1), en(66667000)
I/iNemoSensor( 2410): skip update_delay wanted_accel = 66667000 current delay = 66667000
D/iNemoSensor( 2410): setDelay(): handle(1), en(66667000)
I/iNemoSensor( 2410): skip update_delay wanted_accel = 66667000 current delay = 66667000
I/FavoriteContactNamesSup(25818): get()
I/FavoriteContactNamesSup(25818): get() : Cache hit
I/FavoriteContactNamesSup(25818): get()
I/FavoriteContactNamesSup(25818): get() : Cache hit
E/SEC_COMP_REGS(25818): libOMX.SEC.AVC.Encoder.so
E/SEC_COMP_REGS(25818): Path & libName : /system/lib/omx/libOMX.SEC.AVC.Encoder.so
I/Timeline(25818): Timeline: Activity_idle id: android.os.BinderProxy@273caeb5 time:312773670
E/AudioTrack(25818): AudioTrack::set : Exit
E/SEC_COMP_REGS(25818): libOMX.SEC.M4V.Decoder.so
E/SEC_COMP_REGS(25818): Path & libName : /system/lib/omx/libOMX.SEC.M4V.Decoder.so
E/SEC_COMP_REGS(25818): libOMX.SEC.M4V.Encoder.so
E/SEC_COMP_REGS(25818): Path & libName : /system/lib/omx/libOMX.SEC.M4V.Encoder.so
E/SEC_COMP_REGS(25818): libOMX.SEC.WMV.Decoder.so
E/SEC_COMP_REGS(25818): Path & libName : /system/lib/omx/libOMX.SEC.WMV.Decoder.so
I/MicrophoneInputStream(25818): mic_started com.google.android.apps.gsa.speech.audio.ah@2cf9dc2
D/audio_hw_primary( 1983): select_input_device: AUDIO_DEVICE_IN_BUILTIN_MIC
V/audio_hw_primary( 1983): Changing output device 2 => 2
V/audio_hw_primary( 1983): Changing input device 0 => 4
V/audio_hw_primary( 1983): Set 'Main Mic Switch'.0 to 1
V/audio_hw_primary( 1983): Set 'IN1L Volume'.0 to 22
V/audio_hw_primary( 1983): Set 'MIXINL IN1L Switch'.0 to 1
V/audio_hw_primary( 1983): Set 'MIXINL IN1L Volume'.0 to 1
V/audio_hw_primary( 1983): Set 'AIF1ADCL Source' to 'Left'
V/audio_hw_primary( 1983): Set 'AIF1ADCR Source' to 'Left'
V/audio_hw_primary( 1983): Set 'AIF1ADC1L Mixer ADC/DMIC Switch'.0 to 1
V/audio_hw_primary( 1983): Set 'AIF1ADC1R Mixer ADC/DMIC Switch'.0 to 1
V/audio_hw_primary( 1983): Set 'AIF1ADC1 HPF Mode'.0 to 1
V/audio_hw_primary( 1983): Set 'AIF1ADC1 HPF Switch'.0 to 1
V/audio_hw_primary( 1983): Set 'AIF1ADC1 HPF Switch'.1 to 1
V/audio_hw_primary( 1983): Set 'AIF1ADC1 Volume'.0 to 96
V/audio_hw_primary( 1983): Set 'AIF1ADC1 Volume'.1 to 96
V/audio_hw_primary( 1983): get_next_buffer: read_buf 0x43724008 extended to 4096 bytes
I/Timeline( 2410): Timeline: Activity_windows_visible id: ActivityRecord{2fbc3f30 u0 com.google.android.googlequicksearchbox/com.google.android.voicesearch.intentapi.IntentApiActivity t2161} time:312773716
E/OMXMaster(25818): A component of name 'OMX.ffmpeg.wmv.decoder' already exists, ignoring this one.
I/ACodec  (25818): sampleRate=16000 channels=1 bits=16
E/LocationReceiver(25818): Received bad location: null
W/RecognitionDispatcher(25818): Could not stop engine: 3.
I/MicrophoneInputStream(25818): mic_close com.google.android.apps.gsa.speech.audio.ah@2cf9dc2
W/art     (25818): Native thread exiting without having called DetachCurrentThread (maybe it's going to use a pthread_key_create destructor?): Thread[57,tid=19264,Native,Thread_=0x548e1348,peer=0x134ce0a0,"Thread-11979"]
W/art     (25818): Native thread exiting without having called DetachCurrentThread (maybe it's going to use a pthread_key_create destructor?): Thread[61,tid=19265,Native,Thread_=0x5cc14370,peer=0x134f40a0,"Thread-11983"]
V/audio_hw_primary( 1983): Changing output device 2 => 2
V/audio_hw_primary( 1983): Changing input device 4 => 0
V/audio_hw_primary( 1983): Set 'Main Mic Switch'.0 to 0
V/audio_hw_primary( 1983): Set 'MIXINL IN1L Switch'.0 to 0
I/OMXMaster(25818): clearPlugins: 0 key=5781cd78 value=471cee74
I/OMXMaster(25818): clearPlugins: 1 key=59e3f768 value=0
I/OMXMaster(25818): clearPlugins: 2 key=5d47a9d8 value=58434154
I/OMXClient(25818): Using client-side OMX mux.
E/AudioTrack(25818): AudioTrack::set : Exit
W/art     (25818): Native thread exiting without having called DetachCurrentThread (maybe it's going to use a pthread_key_create destructor?): Thread[59,tid=19263,Native,Thread*=0x5d4466a8,peer=0x134f00a0,"Thread-11982"]
D/iNemoSensor( 2410): setDelay(): handle(0), en(66667000)
I/iNemoSensor( 2410): skip update_delay wanted_accel = 66667000 current delay = 66667000
I/iNemoSensor( 2410): enable(): handle(1), en(0), what(2)
D/iNemoSensor( 2410): enable(): MASK_ACC (1) MASK_MAG (0) MASK_GYR (0), MASK_UMAG(0)
D/iNemoSensor( 2410): enable(): mEnAcc(1) mEnMag(0) mEnGyr(0), mEUMag(0)
I/iNemoSensor( 2410): skip update_delay wanted_accel = 66667000 current delay = 66667000
D/audio_hw_primary( 1983): select_output_device: AUDIO_DEVICE_OUT_SPEAKER
E/SEC_COMP_REGS(25818): .
E/SEC_COMP_REGS(25818): ..
E/SEC_COMP_REGS(25818): libOMX.SEC.AVC.Decoder.so
E/SEC_COMP_REGS(25818): Path & libName : /system/lib/omx/libOMX.SEC.AVC.Decoder.so
E/SEC_COMP_REGS(25818): libOMX.SEC.AVC.Encoder.so
E/SEC_COMP_REGS(25818): Path & libName : /system/lib/omx/libOMX.SEC.AVC.Encoder.so
E/SEC_COMP_REGS(25818): libOMX.SEC.M4V.Decoder.so
E/SEC_COMP_REGS(25818): Path & libName : /system/lib/omx/libOMX.SEC.M4V.Decoder.so
E/SEC_COMP_REGS(25818): libOMX.SEC.M4V.Encoder.so
E/SEC_COMP_REGS(25818): Path & libName : /system/lib/omx/libOMX.SEC.M4V.Encoder.so
E/SEC_COMP_REGS(25818): libOMX.SEC.WMV.Decoder.so
E/SEC_COMP_REGS(25818): Path & libName : /system/lib/omx/libOMX.SEC.WMV.Decoder.so
E/OMXMaster(25818): A component of name 'OMX.ffmpeg.wmv.decoder' already exists, ignoring this one.
I/ACodec  (25818): sampleRate=16000 channels=1 bits=16
I/AudioRouter(25818): Route changed: ROUTE_NO_BLUETOOTH->ROUTE_NO_AUDIO,CONNECTION_TYPE_NONE->CONNECTION_TYPE_NONE
I/MediaFocusControl( 2410):  AudioFocus  abandonAudioFocus() from android.media.AudioManager@902bf52com.google.android.apps.gsa.speech.audio.c.a$1@37e2a223

J’utilise un Galasy S3 GT-I9300 avec Android 5.1.1

Noury

**Comment by N0ury** [comment]
C'est bon, ça fonctionne.
Je n'avais pas vu ça:
Pattern ff = Pattern.compile("Final|fantasy");
J'ai la musique...
Merci

**Comment by N0ury** [comment]
Bonjour Ludovic,

J'ai un peu creusé ce sujet de d'EXTRA_LANGUAGE.
En fait Locale.getDefault() renvoit une Locale.
Il faut utiliser la méthode getDisplayLanguage() pour obtenir la langue dans un String.
C'est pour ça que ça fonctionne bien avec "fr_FR"
Ça donne:
intent.putExtra(RecognizerIntent.EXTRA_LANGUAGE, Locale.getDefault().getDisplayLanguage());
Et là, ça fonctionne bien

À part ce détail, très bon auto

Merci

Noury

**Comment by 1ud0v1c** [comment]
Salut :) !

Oui, cela ne m'étonne pas ^_^, le retour du toString, notamment permettait d'aiguiller sur cette piste. C'est rigolo, que du coup sur ma Nexus 7, je n'ai eu aucun souci. En tout cas, ça va me permettre de mettre à jour le tutoriel et le dépôt. 

Merci d'avoir testé et bon courage pour la suite.
1ud0v1c
